---
- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result
  when:
    (ansible_distribution == 'CentOS') or
    (ansible_distribution == 'Red Hat Enterprise Linux') or
    (ansible_distribution == 'Amazon')

- name: Enable existing EPEL repo.
  # the "yum_repository" module doesn't support this currently, so ....
  ini_file:
    dest: /etc/yum.repos.d/epel.repo
    section: epel
    option: enabled
    value: 1
  when: ansible_distribution == 'Amazon'

- name: Install nonexistant EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"
